[".hammerspoon/Spoons/ShiftIt.spoon"]
    type = "archive"
    url = "https://github.com/peterklijn/hammerspoon-shiftit/raw/master/Spoons/ShiftIt.spoon.zip"
    exact = true
    stripComponents = 1
["{{ .code_directory }}/jackjennings/invoices"]
    type = "git-repo"
    url = "git@github.com:jackjennings/invoices.git"
