[".hammerspoon/Spoons/ShiftIt.spoon"]
    type = "archive"
    url = "https://github.com/peterklijn/hammerspoon-shiftit/raw/master/Spoons/ShiftIt.spoon.zip"
    exact = true
    stripComponents = 1
["{{ .code_directory }}/jackjennings/invoices"]
    type = "git-repo"
    url = "git@github.com:jackjennings/invoices.git"
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["{{ .zsh_custom_directory }}/plugins/zsh-completions"]
    type = "git-repo"
    url = "git@github.com:zsh-users/zsh-completions.git"
